-- migrations/001_create_accounts_table.up.sql
-- GORM will handle table creation based on models.Account struct.
-- This file is kept as a placeholder if manual schema adjustments are needed in the future.
-- No explicit CREATE TABLE statement here for GORM's AutoMigrate.
